In [1]:
import numpy as np
# Predict the output shape BEFORE running each one

a = np.ones((4, 1))
b = np.ones((1, 3))
c = np.ones((4, 3))
d = np.ones((3,))
e = np.ones((4,))
f = np.ones((1,))
g = np.ones((4, 1, 3))
h = np.ones((4, 2, 3))

# Work through each one on paper first, then run:
print((a + b).shape)        # ?
print((a + c).shape)        # ?
print((c + d).shape)        # ?
print((c + e[:,np.newaxis]).shape)        # ? ← this one fails — understand why
print((a + f).shape)        # ?
print((g + h).shape)        # ?
print((a + b + c).shape)    # ?



(4, 3)
(4, 3)
(4, 3)
(4, 3)
(4, 1)
(4, 2, 3)
(4, 3)


NORMALISATION

In [2]:
rng= np.random.default_rng(seed=42)
data= rng.integers(40,100,(5,4)).astype(float)
print("Raw scores",data)


# ── Mean normalisation (subtract column mean) ─────Make each column’s average equal to 0
column_mean= np.mean(data,axis=0)
centered= data-column_mean
print("centered (column_mean subtracted):", centered.round(2))
print("new mean(centered):", np.mean(centered).round(2))

# ── Z-score normalisation (subtract mean, divide by std) ────
#ddof = 0 → whole population known,default value
#ddof = 1 → working with sample data

col_std= np.std(data,axis=0,ddof=1)

z_scores= (data-column_mean)/col_std
print("z_scores: ", z_scores)
print("z_score column_mean:", np.mean(z_scores,axis=0).round(2))
print("z_score std deviation :",np.std(z_scores,axis=0,ddof=1))

# ── Min-Max normalisation (scale to [0, 1]) ─────────────────
column_min= np.min(data,axis=0)
column_max=np.max(data,axis=0)
minmax=(data-column_min)/(column_max-column_min)
print("minmax: ",minmax)
print("new column_min",np.min(minmax,axis=0).round(2))
print("new column max",np.max(minmax,axis=0).round(2))

#row wise normalisation
#keep the number of dimensions the same after the operation instead of reducing them.
row_mean= np.mean(data,axis=1,keepdims=True)#shape of row_mean will be(5,1) instead of (5,)
print("Row mean: ",row_mean)
row_centered= data-row_mean
print("Row centered :", row_centered.round(2))
print("new row_mean:", np.mean(row_centered.round(2),axis=1,keepdims=True))






Raw scores [[45. 86. 79. 66.]
 [65. 91. 45. 81.]
 [52. 45. 71. 98.]
 [84. 85. 83. 87.]
 [70. 47. 90. 67.]]
centered (column_mean subtracted): [[-18.2  15.2   5.4 -13.8]
 [  1.8  20.2 -28.6   1.2]
 [-11.2 -25.8  -2.6  18.2]
 [ 20.8  14.2   9.4   7.2]
 [  6.8 -23.8  16.4 -12.8]]
new mean(centered): 0.0
z_scores:  [[-1.18799563  0.66772077  0.31032433 -1.01541983]
 [ 0.11749407  0.88736576 -1.64356959  0.08829738]
 [-0.73107423 -1.13336814 -0.14941542  1.33917687]
 [ 1.35770929  0.62379177  0.5401942   0.52978426]
 [ 0.4438665  -1.04551015  0.94246648 -0.94183868]]
z_score column_mean: [-0.  0.  0.  0.]
z_score std deviation : [1. 1. 1. 1.]
minmax:  [[0.         0.89130435 0.75555556 0.        ]
 [0.51282051 1.         0.         0.46875   ]
 [0.17948718 0.         0.57777778 1.        ]
 [1.         0.86956522 0.84444444 0.65625   ]
 [0.64102564 0.04347826 1.         0.03125   ]]
new column_min [0. 0. 0. 0.]
new column max [1. 1. 1. 1.]
Row mean:  [[69.  ]
 [70.5 ]
 [66.5 ]
 [84.75]
 [68

Application 4 — Comparing each element to a threshold array ─
Useful in multi-label classification

In [3]:
scores = np.array([[85, 72, 91, 68],
                   [55, 88, 73, 92],
                   [78, 61, 84, 70]])
thresholds = np.array([70, 75, 80, 65])
subjects = ["Math","Physics","CS","English"]
passed= scores>=thresholds
# For each student, which subjects did they pass?
print("Passed: ",(passed))
# How many subjects did each student pass?
print("each student pass subjects:", np.sum(passed,axis=1))
# Which students passed ALL subjects?
print("students passed all subjects:",np.all(passed,axis=1))
# Which subjects were passed by ALL students?
universal= np.all(passed,axis=0)
print("subject passed by all students:",universal)
print("Universal:", np.array(subjects)[universal])



Passed:  [[ True False  True  True]
 [False  True False  True]
 [ True False  True  True]]
each student pass subjects: [3 2 3]
students passed all subjects: [False False False]
subject passed by all students: [False False False  True]
Universal: ['English']


Outer Product

In [4]:
x = np.array([1, 2, 3, 4, 5])     # shape: (5,)
y = np.array([10, 20, 30])  #Shape(3,)
#shape of outer product should be(len(x),len(y))-(5,3)
outer_product=x[:,np.newaxis]*y[np.newaxis,:]
print("result:",outer_product)
#shortcut for outer product
print("shortcut result:", np.outer(x,y))


result: [[ 10  20  30]
 [ 20  40  60]
 [ 30  60  90]
 [ 40  80 120]
 [ 50 100 150]]
shortcut result: [[ 10  20  30]
 [ 20  40  60]
 [ 30  60  90]
 [ 40  80 120]
 [ 50 100 150]]


STACKING ,SPLITTING AND ADVANCED ARRAY MANIPULATION

COMBINING ARRAYS

In [ ]:
# ── Vertical and horizontal stacking ────────────────────────
a= np.array([[1,2,3],
             [4,5,6]])

b= np.array([[7,8,9],
             [10,11,12]])
v= np.vstack((a,b))
print("Vertically stacked:",v,v.shape)

h = np.hstack((a,b))
print("Horizontally stacked:",h,h.shape)

#Concatenation specify axis explicitly
along_rows= np.concatenate((a,b),axis=0)
along_columns= np.concatenate((a,b),axis=1)
print("Along_rows:",along_rows)
print("Along columns:", along_columns)

# np.stack: creates a NEW dimension — different from concatenate
stacked= np.stack((a,b),axis=0) #Whole array stays together
stacked1=np.stack((a,b),axis=1) #interleave rows, same row data grouped together
stacked2=np.stack((a,b),axis=2) #individual elements zipped together
print(f"stacked : {stacked} \n stacked_shape: {stacked.shape}")
print(f"stacked1 : {stacked1} \n stacked1_shape={stacked1.shape}")
print(f"stacked2 : {stacked2} \n stacked2_shape={stacked2.shape}")


# Real use case: combining feature arrays
heights = np.array([[170], [165], [180], [155]])   # shape: (4,1)
weights = np.array([[65],  [58],  [80],  [50]])    # shape: (4,1)
ages    = np.array([[22],  [25],  [19],  [30]])    # shape: (4,1)
features= np.hstack((heights,weights,ages))
print("Features:", features)



SPLITTING ARRAYS

In [ ]:
data = np.arange(1, 25).reshape(4, 6)
#horizontal split
column_parts=np.hsplit(data,2)
for i,part in enumerate(column_parts):
    print(f"column split: {i} shape: {part.shape}")
    print(part)
#vertical split
row_parts= np.vsplit(data,2)
for i , parts in enumerate(row_parts):
    print(f" row split: {i} shape: {parts.shape}")
    print(parts)
    
#



Split at specific indices — like train/val/test splits
position:  0         70        85        100
           |          |         |          |
           [  train  ][   val  ][   test  ]
           70 items    15 items   15 items
train = indices[0:70]
val   = indices[70:85]
test  = indices[85:]

In [ ]:
indices= np.arange(100)
rng.shuffle(indices)#Shuffle shuffles the indices so the data remained in fixed position, so that we will get different types of data across the split
train,val,test=np.split(indices,[70,85])
print(f"Train: {train.shape} Val: {val.shape} Test: {test.shape} ")

In [ ]:
scores = np.array([78, 92, 55, 88, 61, 95, 73])
names = np.array(['Arjun', 'Priya', 'Ravi', 'Sneha', 'Chen', 'Fatima', 'Lakshmi'])
print(f"scores ascending:", np.sort(scores))
print("scores descending:",np.sort(scores)[::-1])
desc_order=np.argsort(scores)[::-1]
for rank, indx in enumerate(desc_order,1):
    print(f"Rank : {rank:<4}  Name: {names[indx]:<10} Score: {scores[indx]}")


In [ ]:

# Sort a 2D array by a specific column
students = np.array([[88, 1],
                     [75, 2],
                     [92, 3],
                     [61, 4],
                     [85, 5]])   # col0=score, col1=student_id
desc_order=np.argsort(students[:,0])[::-1]
print(students[desc_order])

UNIQUE VALUES

In [ ]:
grades = np.array(['B', 'A', 'C', 'A', 'B', 'F', 'B', 'A', 'C', 'A'])
unique_values=np.unique(grades)
print(unique_values)
val,count=np.unique(grades,return_counts=True)
for val,count in zip(val,count):
    bar= "◼️"* count
    print(f"Value: {val} {bar} Count:{count}")

# With inverse — index that maps each element back to unique values
val,inverse= np.unique(grades,return_inverse=True)
print(f" value : {val} Inverse:", inverse)
print(grades[inverse])

In [ ]:
#np.select
scores = np.array([85, 92, 55, 73, 91, 48, 88, 61, 79, 95])
conditions=[scores>=90,scores>=80,scores>=70,scores>=60]
choices=['A','B','C','D']
grades_v2 = np.select(conditions, choices, default='F')
print(grades_v2)

In [ ]:
failing_indices = np.where(scores < 60)
print(failing_indices)
print("Failing: ",np.where(scores<60)[0])

arr = np.array([[10, 70, 50],
                [80, 40, 90]])
rows,columns= np.where(arr<60)
print("Failing :",arr[rows,columns])



In [ ]:
DAY2 PROJECT 
Exam Dataset Full Analysis 

In [ ]:
import numpy as np
rng= np.random.default_rng(seed=42)

n_students=30
n_subjects=5
subject_names=['Math', 'Stats', 'Python', 'ML', 'SQL']
student_ids=np.arange(1,n_students+1)

# Simulate scores with subject difficulty offsets
base= rng.normal(72,14,(n_students,n_subjects))#shape=(30,5)
difficulty=np.array([0, -5, +3, -8, +2])  #(5,)
'''np.clip(array, min, max)
It clamps every value to stay within a range.
pythonnp.clip(x, 0, 100)
# any value below 0  → becomes 0
# any value above 100 → becomes 100
# anything in between → stays as is'''

raw_scores= np.clip(base+difficulty,0,100).round(2)
print("Shape of raw_scores:", raw_scores.shape)
print("First five students:", raw_scores[:5,:])

# ── Task 1: Class statistics per subject ─────────────────────
subj_mean = np.mean(raw_scores,axis=0)#(5,)
subj_std  = np.std(raw_scores,axis=0,ddof=1)
subj_min  = np.min(raw_scores,axis=0)
subj_max  =np.max(raw_scores,axis=0)
print("Subject Statistics")
print('-'*42)
print(f"{'Subject':<7} {'Mean':<6} {'Std':<6} {'Min':<6} {'Max':<6}")
print('-'*42)
for i , name in enumerate(subject_names):
    print(f"{name:<7} {subj_mean[i]:<6.2f} {subj_std[i]:<6.2f} {subj_min[i]:<6.2f} {subj_max[i]:<6.2f}")
# ── Task 2: Z-scores for every student in every subject ──────

z_scores=(raw_scores-subj_mean)/subj_std
print("First five z_scores:", z_scores[:5,:].round(3))
print("z_score_mean:",np.mean(z_scores,axis=0).round(10))
print("z_score_std:",np.std(z_scores,axis=0,ddof=1).round(10))

# ── Task 3: Students above average in ALL subjects ─────────
all_above_avg=np.all(raw_scores>subj_mean,axis=1)#shape(30,)
print(all_above_avg)
print("Students above average in all subjects:",np.sum(all_above_avg))
print("Student ids:",student_ids[all_above_avg])
print("Their scores:",raw_scores[all_above_avg])

## ── Task 4: Each student's strongest and weakest subject ─────
best_subj_indx= np.argmax(raw_scores,axis=1)
worst_subj_indx=np.argmin(raw_scores,axis=1)
#best_subject_inx maps to corresponding column
print(f"{'Student':<15} {'Best Subject':<15} {'Score':<7} {'Worst Subject':<15} {'Score':<7}")
for i in range(0,10):
    print(f"Student {i+1:<7} {subject_names[best_subj_indx[i]]:<15} {raw_scores[i,best_subj_indx[i]]:<7.2f} "
           f"{subject_names[worst_subj_indx[i]]:<15} {raw_scores[i,worst_subj_indx[i]]:<7.2f}")
#Task 5 — rank all 30 students by overall average. 
student_mean=np.mean(raw_scores,axis=1)
rank_order= np.argsort(student_mean)[::-1]#descending order
print('-'*45)
print(f"{'Rank':<5} {'Student ID':<12} {'Average': <10} {'Grade': <7}")
for i,indx in enumerate(rank_order,1):
    grade=  np.where( student_mean[indx]>=90,'A',
              np.where(student_mean[indx]>=80,'B', 
                np.where(student_mean[indx]>=70,'C',
                   np.where(student_mean[indx]>=60,'D','F'))))
    print(f"{i:<5} {student_ids[indx]:<12} {student_mean[indx]:<10.2f} {grade:<7}")

# ── Task 6: Min-Max normalise all scores to [0, 1] ───────────
column_min=np.min(raw_scores,axis=0,keepdims=True)
column_max=np.max(raw_scores,axis=0,keepdims=True)
normalised= (raw_scores-column_min)/(column_max-column_min)
print("Normalised first_five:",normalised[:5,:].round(2))
print("new min per subject:",np.min(normalised,axis=0).round(2))
print("new max per subject:", np.max(normalised,axis=0).round(2))
print(" -"*45)

# ── Task 7: Correlation between subjects ─────────────────────
'''What is correlation?
Correlation measures how strongly two things move together.
For example — do students who score high in Math also tend to score high in Stats? Or is there no relationship at all?
+1.0  → perfect positive  — one goes up, other always goes up
 0.0  → no relationship   — one goes up, other does anything
-1.0  → perfect negative  — one goes up, other always goes down
Conditions for a matrix to be symmetric

A matrix must:

Be square (same rows and columns)
Satisfy
A[i][j] = A[j][i] for all i, j
'''

correl_matrix=np.corrcoef(raw_scores.T)#shape=(5,30) will return (5,5)

#printing correlation matrix

print("Subject correlation matrix:")
print(f"{' ':<10}",end="")
for name in subject_names:
    print(f"{name:>10}",end="")
print()

for i,name in enumerate(subject_names):
    print(f"{name:>10}",end="")
    for j in range(n_subjects):
        print(f"{correl_matrix[i,j]:>10.2f}",end="")
    print()

#to find the most correlated pair
# ignore diagonal
np.fill_diagonal(correl_matrix,0)
correl_max_indx=np.unravel_index(np.argmax(np.abs(correl_matrix)),correl_matrix.shape)#returns a tupe with respective row and column value
print("Most correlated pair:",end="")
print(f"{subject_names[correl_max_indx[0]]} <-> "
      f"{subject_names[correl_max_indx[1]]}  ",end="")
print(f"r({correl_matrix[correl_max_indx].round(2)})")
      



