In [4]:
import numpy as np

In [4]:
a= np.array([1,2,3,4,5,6])

In [6]:
print (a) 


[1 2 3 4 5 6]


In [7]:
b= a[-1:-7:-1]

In [5]:
#slicing can be done in  both row and column a[row , column ]  for a 2d array
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=a[1:2,1:2]
print(b)

[[5]]


In [8]:
print(b)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [18]:
b[1]= 7

In [19]:
print(a)

[1 2 3 4 7 6]


In [20]:
print(b)

[6 7 4 3 2 1]


In [30]:
c= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [29]:
print(basic_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
print(b)

[6 7 4 3 2 1]


In [32]:
print(c[2,2])

9


In [33]:
c.ndim

2

In [34]:
a.ndim

1

In [35]:
c.shape

(3, 3)

In [36]:
c.size

9

In [37]:
c.dtype

dtype('int32')

In [38]:
np.zeros(2)

array([0., 0.])

In [40]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [45]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
np.arange(3)

array([0, 1, 2])

In [47]:
np.arange(4).reshape((2,2))

array([[0, 1],
       [2, 3]])

linspace creates evenly spaced integers between two values

In [3]:
np.linspace(2,10,6)

array([ 2. ,  3.6,  5.2,  6.8,  8.4, 10. ])

In [50]:
arr=np.array([4,6,2,1,4,8,7])

In [51]:
arr.sort()

In [52]:
print(arr)

[1 2 4 4 6 7 8]


In [57]:
a= np.array([[1,2,3],[4,5,6]])
b= np.array([[7,8,9]])
np.concatenate((a,b),axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
c=np.array([[7],[8]])
np.concatenate((a,c),axis=1)

array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

In [4]:
a= np.arange(8)
b= a.reshape(8,1)
print(b)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


In [5]:
print(a.shape)
print(b.shape)

(8,)
(8, 1)


In [9]:
# newaxis creates dimension of size 1  along either row vector or column vector
a= np.array([[1,2,3],[4,5,6],[6,7,8],[7,8,9]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]
 [6 7 8]
 [7 8 9]]
(4, 3)


In [10]:
b= a[np.newaxis,:,:]
print(b)
print(b.shape)

[[[1 2 3]
  [4 5 6]
  [6 7 8]
  [7 8 9]]]
(1, 4, 3)


In [84]:
b= a[:,:,np.newaxis]
print(b)
print(b.shape)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[6]
  [7]
  [8]]

 [[7]
  [8]
  [9]]]
(4, 3, 1)


In [11]:
b=np.expand_dims(a,axis=1)
print(b)

[[[1 2 3]]

 [[4 5 6]]

 [[6 7 8]]

 [[7 8 9]]]


In [10]:
#boolean indexing
#It returns only 1-D flat array as result
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
condition= a[a%3==0]
print(condition)

[3 6 9]


In [90]:
print(a[a<=5])

[1 2 3 4 5]


In [91]:
condition1= a>5
print(condition1)

[[False False False]
 [False False  True]
 [ True  True  True]]


In [93]:
print(np.nonzero(a))

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64), array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))


In [95]:
#nonzero method returns a tuple of array of indices . for a 1-d array it returns an array of indices
#for a 2d array , it returns row indices and column indices 
a= np.array([[1,2,3],[4,5,6]])
print(np.nonzero(a))


(array([0, 0, 0, 1, 1, 1], dtype=int64), array([0, 1, 2, 0, 1, 2], dtype=int64))


In [96]:
rows, columns =np.nonzero(a)
print(a[rows,columns])

[1 2 3 4 5 6]


In [97]:
print(a[np.nonzero(a)])

[1 2 3 4 5 6]


In [101]:
#transpose works only on 3 * 3 matrix
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[np.transpose(np.nonzero(a))]

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [7 8 9]]

 [[4 5 6]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]]

 [[4 5 6]
  [7 8 9]]

 [[7 8 9]
  [1 2 3]]

 [[7 8 9]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]]]


In [103]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[np.nonzero(a>5)])

[6 7 8 9]


In [14]:
#hstack and vstack is used to stack different arrays vertically and horizontally
a1= np.array([[1,2],[3,4]])
a2= np.array([[5,6],[7,8]])
a= np.vstack((a1,a2))
b= np.hstack((a1,a2))
print(a)
print(b)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [15]:
#hsplit splits the array into parts. Give the array and no of parts as input parameters 
np.hsplit(b,2)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]

In [16]:
#The cut happens before column 1 and column 3
np.hsplit(b,(1,3))

[array([[1],
        [3]]),
 array([[2, 5],
        [4, 7]]),
 array([[6],
        [8]])]

In [17]:
# Here b is a view. Modifying it changes the original array as well
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
b=a[0:2]
print(b)
b[1,2]=7
print(a)


[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 7]
 [7 8 9]]


In [119]:
#modifying copy doesnt modify the original array
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
c= a.copy()
c[1,2]=7
print(c)
print(a)

[[1 2 3]
 [4 5 7]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [123]:
#Basic operation in arrays
#ADDITION
a= np.array([[1,2],
            [3,4]])
b= np.array([[10,20]])
print(a+b)


[[11 22]
 [13 24]]


In [4]:
"""Arithmetic operations practise
1. Create array [[1,2,3],[4,5,6],[7,8,9]]
 → add 5 to every element"""
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a+5)
print(a*3)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [6]:
a= np.array([[100,200],[300,400]])
print(a//10)

[[10 20]
 [30 40]]


In [8]:
a= np.array([[1,2,3],[4,5,6]])
print(a**2)

[[ 1  4  9]
 [16 25 36]]


In [12]:
#Element wise operations
a = np.array([[1,2,3],[4,5,6]])
b= np.array([[6,5,4],[3,2,1]])
print(a+b)
print(a-b)
print(a*b)


[[7 7 7]
 [7 7 7]]
[[-5 -3 -1]
 [ 1  3  5]]
[[ 6 10 12]
 [12 10  6]]


In [15]:
a= np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2],[3,4],[5,6]] )
print(a+b)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [19]:
#AGGREGATE FUNCTIONS
a=np.array([[1,2,3],[4,5,6]])
print(np.sum(a,axis=0))
print(np.prod(a))
print(np.max(a))
print(np.argmax(a))
print(np.max(a, axis=1))
print(np.mean(a,axis=0))
print(np.cumsum(a))


[5 7 9]
720
6
5
[3 6]
[2.5 3.5 4.5]
[ 1  3  6 10 15 21]


In [33]:
#Sorting and searching
a=np.array([[6,2,4],[10,8,6]])
print(np.sort(a))
print(np.sort(a,axis=0))
print(np.argsort(a))
#returns the indices of the smallest to largest numbers in the sorted array
# a[argsort] clearly works only on 1-d array 
#print(a[np.argsort(a)])

[[ 2  4  6]
 [ 6  8 10]]
[[ 6  2  4]
 [10  8  6]]
[[1 2 0]
 [2 1 0]]


IndexError: index 2 is out of bounds for axis 0 with size 2

In [36]:
#here argmax flattens array to 1-d array and then returns the index postition for the max or min value
np.argmax(a)
np.argmax(a,axis=0)

array([1, 1, 1], dtype=int64)

In [37]:
np.argmin(a)
np.argmin(a,axis=1)

array([1, 2], dtype=int64)

In [39]:
#Where is same as non zero .
a=np.array([[1,2,3],[4,5,6]])
print(a[np.where(a!=0)])
print(np.where(a>2,1,0))


[1 2 3 4 5 6]
[[0 0 1]
 [1 1 1]]


In [44]:
#Unique - it returns an array of values without duplicates
a=np.array([1,2,3,3,4,5,4,1])
print(np.unique(a))
print(np.unique(a,return_counts=True))
print(np.unique(a,return_index=True))
values,count= np.unique(a,return_counts=True)
print(values)
print(count)

[1 2 3 4 5]
(array([1, 2, 3, 4, 5]), array([2, 1, 2, 2, 1], dtype=int64))
(array([1, 2, 3, 4, 5]), array([0, 1, 2, 4, 5], dtype=int64))
[1 2 3 4 5]
[2 1 2 2 1]


In [46]:
#Unique in a 2d array . first it is flatenned to a 1-D array and then return values according to that array
a=np.array([[1,2,3],[3,2,1],[7,8,9]])
print(np.unique(a))
print(np.unique)


[1 2 3 7 8 9]


In [24]:
#Flatten to convert any array to 1-D
a=np.array([[1,2,3],[3,2,1],[7,8,9]])
print(a.flatten())
print(a)
#To create the transpose of the matrix
print(a.T)


[1 2 3 3 2 1 7 8 9]
[[1 2 3]
 [3 2 1]
 [7 8 9]]
[[1 3 7]
 [2 2 8]
 [3 1 9]]
